[package]
name = "miracle-plugin"
version = "0.0.1"
edition = "2024"
description = "Rust bindings for the miracle-wm plugin API"
license = "GPL-3.0-or-later"
homepage = "https://github.com/miracle-wm-org/miracle-wm"
repository = "https://github.com/miracle-wm-org/miracle-wm"
documentation = "https://docs.miracle-wm.org/"

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]

[lib]
crate-type = ["rlib"]

[dependencies]
bitflags = "2"
glam = "0.29"

[build-dependencies]
bindgen = "0.71"
