name = "miracle-plugin-docs"
compatibility_date = "2026-03-15"

[assets]
directory = "target/doc"

[env.production]
name = "miracle-plugin-docs"
route = { pattern = "docs.miracle-wm.org/*", zone_name = "miracle-wm.org" }
