name: Build & Test - Fedora

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    name: Fedora Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:latest
      - name: Get source
        uses: actions/checkout@v3
        with:
          path: 'miracle-wm'
      - name: Create container and run tests
        run: |
          {
              echo 'FROM fedora:latest'
              echo '# set TZ to ensure the test using timestamp'
              echo 'ENV TZ=America/New_York'
              echo 'RUN dnf -y update'
              echo 'RUN dnf -y install cmake gcc-c++ git-core mir-devel mir-internal-devel glib-devel yaml-cpp-devel json-devel libevdev-devel json-c-devel libnotify-devel gtest-devel gmock-devel libxkbcommon-devel desktop-file-utils pcre2 libglvnd-gles libglvnd-egl libglvnd-devel glm-devel boost-devel mesa-libgbm-devel wasmedge-devel clang-devel'
              echo 'RUN curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
              echo 'ENV PATH="/root/.cargo/bin:${PATH}"'
              echo 'RUN dnf clean all'
              echo 'COPY miracle-wm miracle-wm'
              echo 'WORKDIR /miracle-wm'
              echo 'RUN cmake -DFEATURE_PLUGIN_SYSTEM=1 -Bbuild'
              echo 'RUN cmake --build build'
              echo 'WORKDIR /miracle-wm/build'
              echo 'RUN make install'
              echo 'WORKDIR /miracle-wm'
              echo 'RUN ./build/tests/miracle-wm-tests'
              echo 'WORKDIR /miracle-wm/build'
              echo 'RUN ./miracle-wm-c/test_miracle_wm_c_api '
              echo 'WORKDIR /miracle-wm'
              echo 'RUN rustup target add wasm32-unknown-unknown'
              echo 'RUN cargo build --manifest-path miracle-plugin-rs/Cargo.toml --target wasm32-unknown-unknown'
          } > podmanfile
          podman build --tag fedoralatestmiraclewm -f ./podmanfile
